[package]
name = "kitty-parse"
version.workspace = true
edition.workspace = true

[dependencies]
kitty-meta = { path = "../meta" }
kitty-ast = { path = "../ast" }
chumsky = { workspace = true }
fastnum = "0.1.11"
